add clear call logs feature
ubports/dialer-app pull request #168
Opened 2021-06-30 12:37 UTC by lduboeuf

![screenshot20210630_143534599](https://user-images.githubusercontent.com/11663835/123961444-a9224900-d9b0-11eb-901d-7aab81c3e681.png)
![screenshot20210630_143544046](https://user-images.githubusercontent.com/11663835/123961458-acb5d000-d9b0-11eb-874a-83283decc2cc.png)

2021-07-12 23:07 UTC, Flohack74 commented
Finally! :)

2021-07-29 21:25 UTC, UniversalSuperBox requested changes

2021-07-29 21:25 UTC, UniversalSuperBox commented on src/qml/HistoryPage/HistoryCleaner.qml
> +                text: "Cancel"
Missed a translation

2021-09-13 20:04 UTC, lduboeuf commented
@UniversalSuperBox or @all how to deal with that issue of exposing a "delete all" feature ?

We already can do it with some js, btw

2021-09-29 15:14 UTC, UniversalSuperBox commented
@lduboeuf I would expect a `DROP TABLE` followed by setting it up again would be enough in this case, and would be much faster than transactionally deleting every record.

2021-09-29 15:28 UTC, lduboeuf commented
> @lduboeuf I would expect a `DROP TABLE` followed by setting it up again would be enough in this case, and would be much faster than transactionally deleting every record.

Humm, of course that would be easier and quicker. So you mean no need to provide delete after N months ?
So about my former question, you finally don't see any security issue exposing the "deleteAll" to HistoryManager QML component ?

2021-09-29 18:57 UTC, UniversalSuperBox commented
You asked about deleting *all* history, not a range :P

I'm pretty sure that history-service is unused by anything but messaging-app and dialer-app. If that changes in the future then we should consider locking it down.

2021-09-29 19:14 UTC, lduboeuf commented
ok, my question was not clear sorry.

2021-09-29 19:43 UTC, lduboeuf commented
So to keep that simpler, i could only provide a "deleteAll" method instead of dealing with date range. That would make the history-service PR lighter. I will give a try

2021-09-29 20:03 UTC, UniversalSuperBox commented
I would still try to design a way to delete history past a certain point, rather than the entire history. Deleting the whole history is potentially useful, deleting a part of it more so. It's just a matter of getting the service in order to do such a thing. It might not be easy.

2021-09-29 20:06 UTC, lduboeuf commented
right, ok. So lets keep it like this for now, i will correct the requested change.

2021-11-21 15:10 UTC, Flohack74 commented
@lduboeuf ready to merge?

2021-11-21 16:00 UTC, lduboeuf commented
> @lduboeuf ready to merge?

yes

2021-11-21 16:03 UTC, lduboeuf commented
@Flohack74 see related PR in history-service. Review is still pending it seems, so waiting for approval

2021-11-22 15:18 UTC, Flohack74 commented
Got it, will ping ;)

2021-12-16 13:02 UTC, Flohack74 commented on src/qml/HistoryPage/HistoryCleaner.qml
> +    title:  i18n.tr("Call history")
Please check also here if pot file changes are needed :)

2021-12-16 21:09 UTC, Flohack74 approved these changes

2021-12-16 21:09 UTC, merged